apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  creationTimestamp: 2019-04-11T13:45:33Z
  generation: 2
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: cd
  namespace: kubevirt
  resourceVersion: "109515114"
  selfLink: /oapi/v1/namespaces/kubevirt/deploymentconfigs/cd
  uid: 1428a6bb-5c60-11e9-8619-0cc47a66a2d4
spec:
  replicas: 1
  selector:
    name: cd
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: cd
    spec:
      containers:
      - env:
        - name: OPENSHIFT_ENABLE_OAUTH
          value: "true"
        - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
          value: "true"
        - name: OPENSHIFT_JENKINS_JVM_ARCH
          value: x86_64
        - name: KUBERNETES_MASTER
          value: https://kubernetes.default:443
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: JNLP_SERVICE_NAME
          value: cd-jnlp
        image: openshift/jenkins-2-centos7@sha256:a6e0a1122288625afde9ff5fb548dd48db8dc2768a76b53367818e870c1861a9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: jenkins
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 16Gi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: cd-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cd
      serviceAccountName: cd
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cd-data
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - jenkins
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
      lastTriggeredImage: openshift/jenkins-2-centos7@sha256:a6e0a1122288625afde9ff5fb548dd48db8dc2768a76b53367818e870c1861a9
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-04-11T13:46:17Z
    lastUpdateTime: 2019-04-11T13:46:17Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2019-04-11T13:45:36Z
    lastUpdateTime: 2019-04-11T13:46:19Z
    message: replication controller "cd-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - imageTrigger:
        from:
          kind: ImageStreamTag
          name: jenkins:latest
          namespace: openshift
      type: ImageChange
    message: image change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
