apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"kubevirt","name":"cd-1","uid":"142dc539-5c60-11e9-8619-0cc47a66a2d4","apiVersion":"v1","resourceVersion":"109514973"}}
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: cd
    openshift.io/deployment.name: cd-1
    openshift.io/scc: restricted
  creationTimestamp: 2019-04-11T13:45:36Z
  generateName: cd-1-
  labels:
    deployment: cd-1
    deploymentconfig: cd
    name: cd
  name: cd-1-f35v0
  namespace: kubevirt
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: cd-1
    uid: 142dc539-5c60-11e9-8619-0cc47a66a2d4
  resourceVersion: "109515104"
  selfLink: /api/v1/namespaces/kubevirt/pods/cd-1-f35v0
  uid: 15ef2e20-5c60-11e9-8619-0cc47a66a2d4
spec:
  containers:
  - env:
    - name: OPENSHIFT_ENABLE_OAUTH
      value: "true"
    - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
      value: "true"
    - name: OPENSHIFT_JENKINS_JVM_ARCH
      value: x86_64
    - name: KUBERNETES_MASTER
      value: https://kubernetes.default:443
    - name: KUBERNETES_TRUST_CERTIFICATES
      value: "true"
    - name: JNLP_SERVICE_NAME
      value: cd-jnlp
    image: openshift/jenkins-2-centos7@sha256:a6e0a1122288625afde9ff5fb548dd48db8dc2768a76b53367818e870c1861a9
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 30
      httpGet:
        path: /login
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 420
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    name: jenkins
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /login
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        memory: 16Gi
      requests:
        memory: 16Gi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
        - SYS_CHROOT
      privileged: false
      runAsUser: 1000270000
      seLinuxOptions:
        level: s0:c16,c15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/jenkins
      name: cd-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: cd-token-ppbmc
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: cd-dockercfg-lhm05
  nodeName: n28.dumpty.ci.centos.org
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000270000
    seLinuxOptions:
      level: s0:c16,c15
  serviceAccount: cd
  serviceAccountName: cd
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: cd-data
  - name: cd-token-ppbmc
    secret:
      defaultMode: 420
      secretName: cd-token-ppbmc
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-04-11T13:45:36Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-04-11T13:46:17Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-04-11T13:45:36Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://76261cf3dadaeb3b5d23dbbb6e76f84ed4e22a6d7706533a643dd32f04aebc78
    image: docker.io/openshift/jenkins-2-centos7:latest
    imageID: docker-pullable://172.30.254.79:5000/ember-csi-stage/jenkins-2-centos7@sha256:a6e0a1122288625afde9ff5fb548dd48db8dc2768a76b53367818e870c1861a9
    lastState: {}
    name: jenkins
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-04-11T13:45:38Z
  hostIP: 172.22.6.56
  phase: Running
  podIP: 10.131.3.220
  qosClass: Burstable
  startTime: 2019-04-11T13:45:36Z
