apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
  creationTimestamp: 2019-04-11T13:45:33Z
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: cd
  namespace: kubevirt
  resourceVersion: "109514937"
  selfLink: /oapi/v1/namespaces/kubevirt/routes/cd
  uid: 14284a26-5c60-11e9-8619-0cc47a66a2d4
spec:
  host: cd-kubevirt.apps.ci.centos.org
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cd
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2019-04-11T13:45:33Z
      status: "True"
      type: Admitted
    host: cd-kubevirt.apps.ci.centos.org
    routerName: router
    wildcardPolicy: None
