apiVersion: v1
imagePullSecrets:
- name: cd-dockercfg-lhm05
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"cd"}}'
  creationTimestamp: 2019-04-11T13:45:33Z
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: cd
  namespace: kubevirt
  resourceVersion: "109514959"
  selfLink: /api/v1/namespaces/kubevirt/serviceaccounts/cd
  uid: 1429172d-5c60-11e9-8619-0cc47a66a2d4
secrets:
- name: cd-token-ppbmc
- name: cd-dockercfg-lhm05
