apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-04-11T13:45:33Z
  labels:
    app: jenkins-ephemeral
    template: jenkins-ephemeral-template
  name: cd-jnlp
  namespace: kubevirt
  resourceVersion: "109514945"
  selfLink: /api/v1/namespaces/kubevirt/services/cd-jnlp
  uid: 142cbec2-5c60-11e9-8619-0cc47a66a2d4
spec:
  clusterIP: 172.30.156.43
  ports:
  - name: agent
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: cd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
