apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
  name: test
  namespace: kubevirt
spec:
  host: test-kubevirt.apps.ci.centos.org
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test
    weight: 100
  wildcardPolicy: None
