apiVersion: v1
kind: Service
metadata:
  name: test-jnlp
  namespace: kubevirt
spec:
  ports:
  - name: agent
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
